### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by erika-to-omochi** [erika-to-omochi/be_happy#2]
## **1. プロジェクトディレクトリの作成**

```bash
mkdir be_happy
cd be_happy
mkdir frontend backend
```

---

### **2.1. Next.jsプロジェクトの作成**

```bash
cd frontend
npx create-next-app@latest . --typescript
```

### **2.2. Tailwind CSSのセットアップ**

```bash
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p
```

**`tailwind.config.js`の設定**

```jsx
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**グローバルCSSの設定**

`styles/globals.css`に以下を追加します。

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

---

### **Rails APIプロジェクトの作成**

```bash
cd ../backend
docker run --rm -v $(pwd):/app -w /app ruby:2.7 bash -c "gem install rails && rails new . --api -d postgresql"
```

---

### **4.1. Dockerfileの作成**

**フロントエンド用Dockerfile**

`frontend/Dockerfile`

```
FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
```

**バックエンド用Dockerfile**

`backend/Dockerfile`

```ruby
FROM ruby:3.2

# 必要なパッケージのインストール
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
```

### **4.2. docker-compose.ymlの作成**

プロジェクトルートに`docker-compose.yml`を作成します。

```yaml
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=your_password
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
```

---

### **5.1. データベース設定ファイルの更新**

`backend/config/database.yml`を編集し、以下のように設定します。

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: your_password
  pool: 5

development:
  <<: *default
  database: your_project_name_development
```

---

### **6.1. Dockerコンテナのビルドと起動**

```bash
docker-compose up -d --build
```

### **6.2. データベースの作成**

バックエンドコンテナに入ります。

```bash
docker-compose exec backend bash
```

データベースを作成します。

```bash
rails db:create
```

---

### **7.1. フロントエンドの確認**

ブラウザで`http://localhost:3000`にアクセスし、Next.jsのデフォルトページが表示されるか確認します。

### **7.2. バックエンドの確認**

ブラウザで`http://localhost:3001`にアクセスし、Railsのウェルカムページが表示されるか確認します。

---

**注**：

- `postgres:14`を使用していますが、必要に応じて最新バージョンに変更できます。
- `your_password`は適切なパスワードに置き換えてください。

---

### **9.1. フロントエンドの確認**

ブラウザで`http://localhost:3000`にアクセスし、Next.jsのデフォルトページが表示されるか確認します。

### **9.2. バックエンドの確認**

ブラウザで`http://localhost:3001`にアクセスし、Railsのウェルカムページが表示されるか確認します。

**注**：Rails 7以降、デフォルトでウェルカムページは表示されません。その場合、コントローラーとルートを設定して適切なレスポンスを返すようにしてください。
